### ISSUE TITLE
Missing information about env var

### ISSUE THREAD

**Issue by edno** [adamovittorio/lazy-graphql#6]
For running both `start:services` and `start:gateway` several environment variable need to be set up, but I cannot find information about those in the `README.md` file :cry:

If those variables are not sent, then the command will throw an error like:
```node
@lazy-graphql/gateway:     throw new Error_1.ConfigurationError(`${key} not found in process.env`);
@lazy-graphql/gateway:     ^
@lazy-graphql/gateway: ConfigurationError: USER_SERVICE_URL not found in process.env
```

**start:services** requires `SERVER_ADDRESS` and `SERVER_PORT` to be set. However, once set the process still ran into an error:
```node
@lazy-graphql/user: 09:43:58 ✨ 🧟‍♀️ Graphql User Service started!
@lazy-graphql/user: (node:37029) Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead
@lazy-graphql/user: 09:43:59 ✨ Server listening at http://127.0.0.1:8000
@lazy-graphql/shared: 9:43:59 AM - Found 0 errors. Watching for file changes.
@lazy-graphql/videogame: 09:43:59 ✨ 🕹 Graphql  Videogame Service started
@lazy-graphql/videogame: (node:37034) Warning: The route option `beforeHandler` has been deprecated, use `preHandler` instead
@lazy-graphql/videogame: 09:43:59 🚨 listen EADDRINUSE: address already in use 127.0.0.1:8000
@lazy-graphql/videogame: Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
@lazy-graphql/videogame:     at Server.setupListenHandle [as _listen2] (net.js:1301:14)
@lazy-graphql/videogame:     at listenInCluster (net.js:1349:12)
@lazy-graphql/videogame:     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1488:7)
@lazy-graphql/videogame:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
```

**start:gateway** needs environment variable for each of the service used (eg. `USER_SERVICE_URL`, `VIDEOGAME_SERVICE_URL`)

Could you please provide documentation about list of variables to be set for running the project :pray:

**Comment by adamovittorio** [comment]
@edno I've added a script to generate the `.env` with a local valid configuration, theoretically we must not have sensitive data into the repo, but for the moment I think it's fine; as general docs regarding the env variables, I suggest to go with Typescript interfaces, I think the names are pretty explanatory and in case we can add some ts-docs annotations.
